apiVersion: v1
kind: Service
metadata:
  name: authentication-service-node-port
  namespace: chat-app
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080