apiVersion: v1
kind: Service
metadata:
  name: authentication-service-cluster-ip
  namespace: chat-app
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
  - port: 80
    targetPort: 80