apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-ingress
  namespace: chat-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"

    # 🔥 REQUIRED for React/Vite SPA
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        # FRONTEND
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend-cluster-ip
              port:
                number: 80

        # AUTH API
        - path: /api/Authentication(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: authentication-service-cluster-ip
              port:
                number: 80

        # USERS API
        - path: /api/Users(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: user-service-cluster-ip
              port:
                number: 80

        # CHAT API
        - path: /api/Chat(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: chatting-cluster-ip
              port:
                number: 80

        # NOTIFICATIONS API
        - path: /api/Notifications(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: notification-cluster-ip
              port:
                number: 80
