apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-ingress
  namespace: chat-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/Authentication/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: authentication-service-cluster-ip
            port:
              number: 80

      - path: /api/Users/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service-cluster-ip
            port:
              number: 80

      - path: /api/Chat/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: chatting-cluster-ip
            port:
              number: 80

      - path: /api/Notifications/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: notification-cluster-ip
            port:
              number: 80

      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-cluster-ip
            port:
              number: 80
