apiVersion: v1
kind: Service
metadata:
  name: notification-cluster-ip
  namespace: chat-app

spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
  - port: 80
    targetPort: 80