apiVersion: v1
kind: Service
metadata:
  name: user-service-cluster-ip
  namespace: chat-app

spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 80